production: true
proxy: "edge"
httpRelativePath: "/keycloak/"
auth: 
  existingSecret: ${KEYCLOAK_SECRET}
  adminUser: ${KEYCLOAK_ADMIN_USER}
  passwordSecretKey: ${KEYCLOAK_ADMIN_PASSWORD_SECRET_KEY}
ingress:
  enabled: true
  servicePort: "http"
  hostname: ${INGRESS_HOSTNAME}
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "30"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "30"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "30"
    nginx.ingress.kubernetes.io/proxy-buffer-size: 2m
    nginx.org/client-max-body-size: "0"
postgresql:
  enabled: false
externalDatabase:
  database: "keycloak_db"
  host: "keycloak-postgresql.${NAMESPACE}.svc.cluster.local"
  user: ${POSTGRES_USER}
  existingSecret: ${KEYCLOAK_SECRET}
  existingSecretPasswordKey: ${POSTGRES_PASSWORD_SECRET_KEY}
nodeSelector:
  "cosmotech.com/tier": "services"
tolerations:
- key: "vendor"
  operator: "Equal"
  value: "cosmotech"
  effect: "NoSchedule"
commonLabels:
  "networking/traffic-allowed": "yes"
global:
  security:
    allowInsecureImages: true
image:
  repository: "bitnamilegacy/keycloak"  